<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="Entriqa.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Entriqa.Domain\Entriqa.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Entriqa.Tests" />
  </ItemGroup>
</Project>
